apiVersion: v1
kind: Pod
metadata:
  name: web-server-test
spec:
  containers:
   - name: web-server-test
     image: nginx
     ports:
     - containerPort: 80
     volumeMounts:
     - mountPath: /var/lib/www/html
       name: mypvc
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: csi-longhorn-pvc
       readOnly: false

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: web-server-test
  name: web-server-test
spec:
  selector:
    app: web-server-test
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
