# This YAML file contains RBAC API objects,
# which are necessary to run external csi attacher for cinder.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher
  namespace: longhorn-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-attacher-runner
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role
subjects:
- kind: ServiceAccount
  name: csi-attacher
  namespace: longhorn-system
roleRef:
  kind: ClusterRole
  name: external-attacher-runner
  apiGroup: rbac.authorization.k8s.io
---

kind: Service
apiVersion: v1
metadata:
  name: csi-attacher
  labels:
    app: csi-attacher
  namespace: longhorn-system
spec:
  selector:
    app: csi-attacher
  ports:
  - name: dummy
    port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-attacher
  namespace: longhorn-system
spec:
  serviceName: "csi-attacher"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-attacher
    spec:
      serviceAccount: csi-attacher
      containers:
      - name: csi-attacher
        image: quay.io/k8scsi/csi-attacher:v0.2.0
        ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 2
          failureThreshold: 1
        args:
        - "--v=5"
        - "--csi-address=$(ADDRESS)"
        env:
        - name: ADDRESS
          value: /var/lib/kubelet/plugins/io.rancher.longhorn/csi.sock
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/kubelet/plugins/io.rancher.longhorn
      - name: liveness-probe
        imagePullPolicy: Always
        image: quay.io/k8scsi/livenessprobe
        args:
        - --csi-address=/var/lib/kubelet/plugins/io.rancher.longhorn/csi.sock
        - --connection-timeout=3s
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/kubelet/plugins/io.rancher.longhorn
      volumes:
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/io.rancher.longhorn
          type: DirectoryOrCreate
